sudo: false

language: php

php:
  - 7.0
  - 7.1
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

install:
  - travis/install-uv.sh
  - travis/install-ev.sh
  - travis/install-event.sh
  # --ignore-platform-reqs, because https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2722
  - composer update -n --prefer-dist --ignore-platform-reqs
  - composer show

script:
  # Run testNoMemoryLeak separately, as those are skipped with enabled coverage
  - php vendor/bin/phpunit --filter testNoMemoryLeak
  - phpdbg -qrr vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml --verbose
  - PHP_CS_FIXER_IGNORE_ENV=1 php vendor/bin/php-cs-fixer --diff --dry-run -v fix

after_script:
  - composer require satooshi/php-coveralls dev-master
  - php vendor/bin/coveralls -v

cache:
  directories:
    - $HOME/.composer/cache/files
