sudo: false

language: php

php:
  - 7.0
  - 7.1
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

install:
  - git clone https://github.com/libuv/libuv;
    pushd libuv;
    git checkout $(git describe --tags);
    ./autogen.sh;
    ./configure --prefix=$(dirname `pwd`)/libuv-install;
    make;
    make install;
    popd;
    git clone https://github.com/bwoebi/php-uv.git;
    pushd php-uv;
    phpize;
    ./configure --with-uv=$(dirname `pwd`)/libuv-install;
    make;
    make install;
    popd;
    echo "extension=uv.so" >> "$(php -r 'echo php_ini_loaded_file();')";
    
  - curl -LS https://pecl.php.net/get/ev | tar -xz;
    pushd ev-*;
    phpize;
    ./configure;
    make;
    make install;
    popd;
    echo "extension=ev.so" >> "$(php -r 'echo php_ini_loaded_file();')";

  - curl -LS https://pecl.php.net/get/event | tar -xz;
    pushd event-*;
    phpize;
    ./configure --with-event-core --with-event-extra --with-event-pthreads;
    make;
    make install;
    popd;
    echo "extension=event.so" >> "$(php -r 'echo php_ini_loaded_file();')";

  - composer update -n --prefer-source
  - composer show

script:
  - phpdbg -qrr vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
  - php vendor/bin/php-cs-fixer --diff --dry-run -v fix

after_script:
  - composer require satooshi/php-coveralls dev-master
  - php vendor/bin/coveralls -v
  
cache:
  directories:
    - $HOME/.composer/cache
