sudo: false

language: php

php:
  - 7.0
  - 7.1
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini

install:
  - travis/install-uv.sh
  - travis/install-ev.sh
  - travis/install-event.sh

  # --ignore-platform-reqs, because https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2722
  - composer update -n --prefer-dist --ignore-platform-reqs
  - composer require satooshi/php-coveralls dev-master --ignore-platform-reqs

  - mkdir -p coverage/cov coverage/bin
  - wget https://phar.phpunit.de/phpcov.phar -O coverage/bin/phpcov
  - chmod +x coverage/bin/phpcov

  - composer show

script:
  # Run testNoMemoryLeak separately, as those are skipped with enabled coverage
  - php vendor/bin/phpunit --verbose --group memoryleak
  - phpdbg -qrr vendor/bin/phpunit --verbose --exclude-group memoryleak --coverage-php coverage/cov/main.cov
  - PHP_CS_FIXER_IGNORE_ENV=1 php vendor/bin/php-cs-fixer --diff --dry-run -v fix

after_script:
  - coverage/bin/phpcov merge --clover build/logs/clover.xml coverage/cov
  - php vendor/bin/coveralls -v

cache:
  directories:
    - $HOME/.composer/cache/files
